### ISSUE TITLE
JAX-RS instrumentation, and other java frameworks

### ISSUE THREAD

**Issue by pavolloffay** [opentracing/contrib#4]
@bensigelman @adriancole Hello,

lately, I was working on JAX-RS instrumentation [1]. I'm planning to add other java frameworks.

Could it be moved to [opentracing-contrib organization](https://github.com/opentracing-contrib)? 

[1]: https://github.com/pavolloffay/opentracing-java-integrations

**Comment by codefromthecrypt** [comment]
as far as I can tell, there's no formalities needed for contrib. Ben, do
you have any opinion? If not, it is a simple matter of repo move, right?

**Comment by bhs** [comment]
@pavolloffay I'd be happy to create a repo for this in opentracing-contrib, sure. My first instinct would be to give each framework its own git repo, though, rather than bundling them... what do you think? I don't want to make your development process too annoying :)

**Comment by pavolloffay** [comment]
Separate repositories work fine with me, however if they share some a common code it thought It would be better to keep them in one repo. (e.g. like in brave) @adriancole what do you think?

Before moving the repository I would like to change groupid and artefactid to:
```
 <groupId>io.opentracing.contrib</groupId>
 <artifactId>opentracing-jaxrs</artifactId>
```

**Comment by codefromthecrypt** [comment]
java instrumentation projects do tend to be mono-repo in nature, at least
while stabilizing it helps a lot. It eventually can get out of control :P
Beyond java, ex zipkin-js is still mostly monorepo for the same reasons
(easy evolution at the tradeoff of more work for maintainers)

**Comment by pavolloffay** [comment]
@bensigelman What do you think? I would vote for mono-repo. It can speed up things.

**Comment by bhs** [comment]
@pavolloffay https://github.com/opentracing-contrib/java-jaxrs/invitations :)

**Comment by bhs** [comment]
@pavolloffay re mono-repos: I could be convinced to change things in the future, but there are already a handful of other Java instrumentation (micro)repos in the contrib org and it seems weird to have *both* a monorepo and microrepo convention happening concurrently. Make sense?? We can certainly adjust in the future if it's making your dev process unmanageable.

**Comment by pavolloffay** [comment]
@bensigelman thanks, I will submit PR shortly.
